# Generated by Django 4.2.7 on 2025-11-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('frequency', models.IntegerField(default=0)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-frequency', 'skill_name'],
                'indexes': [models.Index(fields=['-frequency'], name='jobdata_ski_frequen_705acd_idx'), models.Index(fields=['skill_name', 'role'], name='jobdata_ski_skill_n_d68ea3_idx')],
                'unique_together': {('skill_name', 'role')},
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('posted_date', models.DateField()),
                ('salary_min', models.FloatField(blank=True, null=True)),
                ('salary_max', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('job_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-posted_date', '-scraped_at'],
                'indexes': [models.Index(fields=['-posted_date'], name='jobdata_job_posted__451eaf_idx'), models.Index(fields=['job_title', 'company'], name='jobdata_job_job_tit_24d14d_idx')],
                'unique_together': {('job_title', 'company', 'posted_date')},
            },
        ),
    ]
