# Generated by Django 4.2.7 on 2025-11-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead/Principal')], default='mid', max_length=20),
        ),
    ]
