# Generated by Django 4.2.7 on 2025-11-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdata', '0002_jobposting_experience_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('date_range', models.IntegerField(default=30, help_text='Number of days')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for anonymous users', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'session_id'], name='jobdata_use_timesta_15f90c_idx')],
            },
        ),
    ]
